apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackerweb-deployment
  labels:
    app: hackerweb-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackerweb-app
  template:
    metadata:
      labels:
        app: hackerweb-app
    spec:
      containers:
        - name: hckrwebapp
          image: akelarmrf/hackerweb:v1
          ports:
            - containerPort: 8000
